"""Add default values for created_at and updated_at on Project

Revision ID: 2a864f58f387
Revises: 6ffd8dcb5f0c
Create Date: 2025-11-22 14:17:57.885014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a864f58f387'
down_revision: Union[str, Sequence[str], None] = '6ffd8dcb5f0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
