"""Apply ORM model updates (Task and User relationships)

Revision ID: 6ffd8dcb5f0c
Revises: cab3c1c81049
Create Date: 2025-11-19 18:45:07.991771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ffd8dcb5f0c'
down_revision: Union[str, Sequence[str], None] = 'cab3c1c81049'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('author_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tasks', 'users', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'author_id')
    # ### end Alembic commands ###
