"""Add due_date to Project model

Revision ID: c158341f54ee
Revises: 2a864f58f387
Create Date: 2025-11-22 20:15:54.327161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c158341f54ee'
down_revision: Union[str, Sequence[str], None] = '2a864f58f387'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('dub_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'dub_date')
    # ### end Alembic commands ###
